name: train_esrnet_x4_sgd
model_type: SRSimpleGatedDegradationModel
scale: 4
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 2 GPUs
manual_seed: 0

# ----------------- options for synthesizing training data in SRSimpleGatedDegradationModel ----------------- #

# simple degradation process
noise_range: [1, 30]
gray_noise_prob: 0.4
jpeg_range: [40, 95]

gt_size: 192
queue_size: 120

# dataset and data loader settings
datasets:
  train:
    name: DF2K+OST
    type: GatedDegradationDataset
    dataroot_gt: datasets/DF2K+OST
    meta_info: datasets/meta_info_DF2K_multiscale_OST_sub.txt
    io_backend:
      type: disk

    blur_kernel_size: 21
    kernel_list: ['iso']
    kernel_prob: [1]

    # below not used
    sinc_prob: 0
    blur_sigma: [0.1, 3]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    gt_size: 192
    use_hflip: True
    use_rot: False

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 500000, 750000, 1000000]
    gamma: 0.5

  total_iter: 500
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
